apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test-deployment
  labels:
    app: kube-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-test
  template:
    metadata:
      labels:
        app: kube-test
    spec:
      containers:
        - name: kube-test-container
          image: nginx:latest
          ports:
            - containerPort: 80
