# .github/workflows/test.yml
name: Test Submodules

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 트리거
  pull_request:
    branches:
      - main # main 브랜치로 풀 리퀘스트가 생성될 때 트리거

jobs:
  test:
    runs-on: ubuntu-latest # 최신 Ubuntu 환경에서 실행

    steps:
      # 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          git submodule status

      - name: Remove GitHub Actions cache
        run: |
          rm -rf .git/modules/test-repo1
          rm -rf .git/modules/test-repo2
          git submodule deinit -f --all

      - name: List repo1 contents
        run: ls test-repo1/

      - name: List repo1 contents
        run: ls test-repo2/

      # Python 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # 원하는 Python 버전 설정

      - name: Find and merge all requirements
        run: |
          find . -type f -name "requirements.txt" -exec cat {} + > combined-requirements.txt
          sort combined-requirements.txt | uniq > combined-requirements-deduped.txt

      # 의존성 설치 (필요한 경우)
      - name: Install dependencies
        run: |
          pip install -r combined-requirements-deduped.txt

      # 테스트 실행
      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}/test-repo1:${{ github.workspace }}/test-repo2
        run: python3 -m unittest integration_tests/test_integration.py
